name: 'Upload a Build Artifact to Azure Blob Storage'
description: 'Upload a build artifact that can be used by subsequent workflow steps to Azure Blob Storage'
author: 'fixpoint'
branding:
  icon: 'sunrise'
  color: 'gray-dark'
inputs:
  connection-string:
    description: 'Connection string'
    required: true
  name:
    description: 'Artifact name'
    required: true
  path:
    description: 'Directory containing files to upload'
    required: true
  container:
    description: 'Container name'
    required: false
    default: 'github-action-artifacts'
  cleanup:
    description: 'Remove all blobs under the target blob (use "true" to enable this option)'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
