# Original version
# https://github.com/actions/checkout/blob/11bd71901bbe5b1630ceea73d27597364c9af683/.github/workflows/update-main-version.yml
name: Update Main Version
run-name: Move ${{ github.event.inputs.major_version }} to ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: The tag or reference to use
        required: true
      major_version:
        type: choice
        description: The major version to update
        options:
          - v4

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Tag new target
        run: git tag -f ${{ github.event.inputs.major_version }} ${{ github.event.inputs.target }}
      - name: Push new tag
        run: git push origin ${{ github.event.inputs.major_version }} --force
